charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml
Related: https://github.com/foxglove/data-platform/issues/773
=> Add support for gcp-cloud-credential volume with credentials.json for gcp

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml
- https://github.com/foxglove/data-platform/pull/787
=> Update edge controller to 61c70bcdefc6cb76fcb789293d7548527b6b3fce

charts/edge-site/templates/statefulset.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/stream-service.yaml
```
- value: /secrets/credential.json
+ value: /secrets/credentials.json
```
As per docs in https://foxglove.dev/docs/data-platform/edge-sites/configure-cloud-credentials
=> Fix small typo in credential_s_.json

charts/edge-site/Chart.yaml, charts/primary-site/Chart.yaml
- Remove the ./ prefix from edge controller recording paths
- Remove unused site-info response fields
=> Update appVersion to d0f1484ad9da5ab77ed08e07169e46a3ceab3777

charts/edge-site/Chart.yaml
This includes a few new metrics for monitoring edge sites.
=> Update edge site to e254b6c594391c9e378330871b20fb74f1bba1e1

charts/primary-site/templates/services/stream.yaml, charts/primary-site/values.yaml
Allow a deployer to add annotations to the stream service.
=> Add streamService service annotations value

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
Updates the primary site helm chart and enables passing of configuration information via env vars.
=> Update primary site helm chart

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml
=> edge-site: configure bucket name in chart

charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml
This became required in a change a couple weeks ago.
=> Set lake bucket name in garbage collector

charts/primary-site/Chart.yaml
This will catch the update for preservation of channel metadata in merged output.
=> Bump primary site image

charts/edge-site/Chart.yaml
This will add support for the autoImport flag.
=> Bump version of edge chart

charts/primary-site/Chart.yaml
This will reduce memory consumption in the stream service and inbox listener.
=> Bump chart version

charts/primary-site/Chart.yaml
This will pull in a fix for a buffer reuse bug in the stream service.
=> Update primary site chart to latest

charts/primary-site/Chart.yaml
This adds support for recordings without devices.
=> Bumps the version of the primary site chart

charts/edge-site/Chart.yaml, charts/primary-site/Chart.yaml
Updates appversion to include the fix from https://github.com/foxglove/data-platform/commit/083ea7cd15e5ca942125c5a3efaf0caa6fbd5d3e
=> Re-release ARM64 images

charts/edge-site/Chart.yaml, charts/primary-site/Chart.yaml
- Edge sites support changing schema names for a topic
- Primary sites updated cors configuration for stream server
=> Update app version to latest release

charts/primary-site/Chart.yaml
- Fixed an issue in the `inbox-listener` that would prevent imports affected by transient network errors from being retried.
=> primary-site: update version

charts/edge-site/Chart.yaml
- Edge-controller: fix a bug in v0.0.23 where new recordings might trigger an internal conflict when they have the same topics as previous recordings.
See https://github.com/foxglove/data-platform/pull/1154 for details.
</td><td>
=> edge-controller: bump to include fix for topic conflict

charts/edge-site/Chart.yaml
- Edge controller: fix garbage collector configuration (#1166)
- 8cc21aa Bump golang.org/x/net from 0.17.0 to 0.23.0 in all modules (#1151)
- eca9fc9 edge-controller: validate device name on POST request (#1163)
- fba8d32 mcap: update to v1.4.0 (#1160)
None.
</td><td>
=> edge-site: update chart

charts/edge-site/Chart.yaml
Fix: Use correctly built multiarch image
</td><td>
=> Bump edge site version

charts/primary-site/Chart.yaml
Release primary-site 0.0.47
</td><td>
=> release primary-site 0.0.47

charts/primary-site/Chart.yaml
- https://github.com/foxglove/data-platform/pull/1340
None.
</td><td>
=> primary-site: bump version

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/_inbox-container.tpl, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
=> Add proxy configuration for primary site templates

charts/primary-site/Chart.yaml
- Fix: remove a cache optimization which could result in data corruption between MCAP channels in some cases
https://github.com/foxglove/docs/pull/585
=> Bump primary site: 0.0.61

charts/primary-site/Chart.yaml
- Fixed: fixed an issue where the stream server would sometimes yield messages from earlier than expected when using the `lastPerChannel` replay policy.
- Fixed: fixed an issue where too many concurrent connections to the underlying object store would result in resource exhaustion. There is now a default limit of 1024 concurrent connections.
</td><td>
=> bump primary site to v0.0.66

charts/primary-site/Chart.yaml
- `inbox-listener`: added `max_finalization_worker_count` environment variable to configure the maximum worker count used to write files to the lake. This defaults to 40 and can be reduced to mitigate rate-limiting API errors from the lake bucket. When set to 0, the inbox listener uses one worker per topic in the input file.
https://github.com/foxglove/docs/pull/678
</td><td>
=> primary-site: update to v0.0.67

charts/primary-site/Chart.yaml
- stream_service: fixed bug where azure users could not authenticate using CLIENT_ID / CLIENT_SECRET as documented.
</td><td>
=> primary-site: bump to 0.0.68

charts/primary-site/Chart.yaml
`inbox-listener`: add support for projects. This change includes writing to a new lake path format.
=> primary-site: bump to 0.0.69

charts/primary-site/Chart.yaml
- stream server: improve memory usage when merging very many files
</td><td>
=> primary-site-0.0.73

.github/workflows/ci.yml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, tests/docker-compose.yaml, tests/test-primary-site-chart.sh
None
None
Adds in some simple tests that will run on pull requests and validate that the helm chart installs correctly and the pods are created.
Fixes FIRE-6.
=> Add simple tests for primary site chart

charts/primary-site/Chart.yaml
- query-server: support metadata from indexed files
None
Updates to support metadata on indexed files.
=> primary-site: 0.0.78
