charts/primary-site/.helmignore, charts/primary-site/Chart.yaml, charts/primary-site/templates/NOTES.txt, charts/primary-site/templates/secret.yaml, charts/primary-site/values.yaml
Add a mostly empty chart for primary-site. We'll populate this chart in follow-up work items (ticketed in linear) as the various components become testable.
=> Add primary-site chart

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml
This updates the edge controller to https://github.com/foxglove/data-platform/commit/dcb5b4812e4d0a6054638ea43712f2e7ee5050ab, which reads retention period configuration from the control plane.
The version is bumped to 0.0.1, no longer alpha.
=> Release edge-site 0.0.1

charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/templates/secret.yaml, charts/primary-site/templates/serviceaccount/inbox-listener.yaml, charts/primary-site/values.yaml
Notes / to discuss:
(Solved, needed a more up to date container)
(Solved, configurable through `azure:` ...)
Docs PR: https://github.com/foxglove/website/pull/916
=> Primary sites helm chart with inbox-processor deployment

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/templates/services/stream.yaml
Add stream service.
Add liveness and readiness probes to stream service deployment to simplify ingress setup. The GKE ingress looks for a readinessProbe and makes that the backend config readiness check during setup.
=> Update to latest version

charts/edge-site/templates/secret.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml, charts/primary-site/templates/secret.yaml
Camel case seems to be the more popular approach to values in helm charts and this aligns edge sites with primary sites chart values
=> Update edge site chart values to camel case

charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml, charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
The AWS credentials are already added to the secret as described in [the docs](https://foxglove.dev/docs/data-platform/primary-sites/configure-cloud-credentials), but the go library requires knowledge about the aws region. This can be loaded from the environment as well as from the `~/.aws/config` file, but only if the `AWS_SDK_LOAD_CONFIG` variable is set:
https://docs.aws.amazon.com/sdk-for-go/api/aws/session/
=> AWS-specific environment variables

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml
The provider and bucket name are now required configuration values for edge sites. Rather than require the user to configure this information in the UI we require this configuration in the values when the deployment is setup. The user must specify this information when deploying their edge site.
Related data platform change: https://github.com/foxglove/data-platform/pull/808/
=> Add upload provider and bucket name as required helm values

charts/primary-site/Chart.yaml, charts/primary-site/templates/ingress.yaml, charts/primary-site/values.yaml
Provide an ingress resource with the default installation. The user can configure aspects of the ingress like annotations. The user can disable the ingress if they want to deploy their own.
=> primary-site: add ingress resource

charts/edge-site/Chart.yaml, charts/edge-site/templates/service.yaml, charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/templates/services/stream.yaml, charts/primary-site/values.yaml
Adds a deployment template for the site controller, with a metrics port
associated with the pod. Enables users to put custom pod labels on the
inbox listener, stream service, and site controller, so that they may
opt these deployments into scraping executed by some external framework
on the basis of labels.
For instance, if a prometheus PodMonitor is set up to scrape pods with
label monitoring: true, this can now be accomplished through the chart.
=> Enable metrics in helm charts

charts/primary-site/Chart.yaml, charts/primary-site/templates/ingress.yaml, charts/primary-site/values.yaml
Adds a `tls` section to the Ingress config as well as to the example `values.yaml`
For context, when running the services on Azure AKS, ssl is likely to be terminated on the ingress controller. Until now, our implementation didn't have a way to customize the `tls` section there — this PR is to remedy that.
=> enhancement(Ingress): tls config for the primary site

charts/edge-site/Chart.yaml, charts/edge-site/templates/service.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml, charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
Bumps versions to add new metrics to the edge controller, documented here: https://github.com/foxglove/website/pull/1003. Adds service labels to the edge controller service. Adds configuration ability for namespace/subsystem of the metrics, which will allow the user to add scoping to the names in prometheus.
=> Add new edge controller metrics and support

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
This PR updates the primary site chart to allow setting custom annotations.
**Description**
In our EKS cluster we're using [AWS Distro for OpenTelemetry](https://aws-otel.github.io/) to scrape metrics from Foxglove services. Most of the default ADOT collector configurations make use of [`<kubernetes_sd_config>`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) to find scrape targets, it seems to be the popular pattern in AWS documentation. Pods to be monitored need to be annotated as shown below to make that work
```yaml
prometheus.io/scrape: true
prometheus.io/port: 6001
prometheus.io/path: /metrics
```
=> Allow setting annotations on primary site services

charts/primary-site/templates/ingress.yaml, charts/primary-site/values.yaml
Allow a deployer to override the host value for an ingress
=> Add `host` value to ingress

charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/stream-service.yaml
Now uses the correct secret `gcp-cloud-credentials` in the lookup. I also added comments to ensure we don't accidentally remove the lookup and cause mayhem.
=> Remove conditional env var for GOOGLE_APPLICATION_CREDENTIALS

charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/stream-service.yaml
Prior to this commit, the name of the credential secret was mispluralized in the inbox listener's lookup call.
=> Fix GCP cloud credential secret

charts/edge-site/Chart.yaml, charts/edge-site/values.yaml, charts/primary-site/Chart.yaml, charts/primary-site/values.yaml
Update edge and primary site deployments to the latest versions. Also fix an issue with passing in env vars via a list: the default value that was in place was an empty map, and helm threw an error if that were overwritten with an array.
=> Updates deployments of edge and primary sites

charts/primary-site/Chart.yaml
Primary site chart version bump to 0.0.15 — forgot to do this in the AWS PR, sorry!
Previous action failed on this: https://github.com/foxglove/helm-charts/actions/runs/4504054942
=> primary site chart version bump to 0.0.15

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml
Allows configuration of an S3-compatible service for recording storage.
=> edge-controller: add env vars to configure minio as storage provider

charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/values.yaml
There should be no public facing changes to existing deployments, however this now enables adding environment variables to the garbage collector via values.yaml.
Add the same env override section as seen in other services to the garbage collector.
Tested locally to confirm that this will not break an existing deployment.
=> FG-3060: Add Env Overrides to Garbage Collector Job

charts/primary-site/Chart.yaml, charts/primary-site/values.yaml
Bumps the image for primary sites to incorporate latest bug fix from data-platform.
=> Make AWS multipart writer part size configurable

charts/edge-site/Chart.yaml, charts/primary-site/Chart.yaml
Release for supporting `deviceName` in foxglove metadata: https://github.com/foxglove/data-platform/pull/961
=> Release deviceName metadata

charts/edge-site/Chart.yaml, charts/edge-site/templates/secret.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml, charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/templates/secret.yaml, charts/primary-site/values.yaml
Customers deploying a primary site or an edge site will be able to define Kubernetes Secrets to load as environment variables by listing them in `.Values.globals.secrets`. This is primarily so that customers do not have to include the Foxglove site token in plain text in values.yaml, however it allows for supporting other customer-provided secrets. The existing method of using `.Values.globals.site_token` will still work until we can safely remove it.
Adds a new section in values.yaml to define Kubernetes Secrets that will be loaded into the environment for all containers via   envFrom directives. Wraps all of the code that currently depends on `.Values.globals.site_token` in conditional blocks so that if `site_token` is blank they are not evaluated. The edge controller now supports both …
=> FG-3744: Support User-Provided Secrets in Helm Charts

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml
Enables adding pod annotations to the edge controller for edge site installations
Adds podAnnotations and podLabels keys to values.yaml, enabling these keys to be added to the edge controller statefulset.
=> FG-4471: Add podAnnotations to Edge Site Helm Chart

charts/primary-site/Chart.yaml
This will fix a problem for Azure setups in identifying the case when a file does not exist.
=> Bump chart version to 0.0.28

charts/primary-site/Chart.yaml
This will allow users to configure the stream service for more even throughput, especially when dealing with large numbers of connections.
=> Update helm charts

charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
Adding support for nodeSelector(s) on deployments
We are currently running two clusters, x86 and ARM64. We want to migrate to a single cluster (currently only ARM64) with an additional NodePool for x86 services, of which Foxglove is the primary. In order to target Foxglove to those nodes (and not the ARM64), we need to be able to set nodeSelectors on the deployments.
=> Add support for nodeSelector on deployments

charts/edge-site/Chart.yaml, charts/primary-site/Chart.yaml
* Our primary site and edge site charts can now be deployed to arm64 clusters.
* https://github.com/foxglove/data-platform/pull/1050
* https://github.com/foxglove/data-platform/pull/1043
* https://github.com/foxglove/data-platform/pull/1041
=> appVersion: update to include arm64 builds

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/stream-service.yaml
- https://github.com/foxglove/data-platform/pull/1098 inadvertently changed the destination path of the stream server image from `stream-service` to `stream-server`. This is the only docker image where the image has a different name from the underlying binary. It's a small difference and was missed. However, this is causing the helm chart to fail to launch the stream server:
```
j@192-168-1-105 helm-charts % docker run us-central1-docker.pkg.dev/foxglove-images/images/stream-service:083ea7cd15e5ca942125c5a3efaf0caa6fbd5d3e   
Unable to find image 'us-central1-docker.pkg.dev/foxglove-images/images/stream-service:083ea7cd15e5ca942125c5a3efaf0caa6fbd5d3e' locally
docker: Error response from daemon: manifest for us-central1-docker.pkg.dev/foxglove-images/images/stream-service:083ea7cd15e5ca942 …
```
=> stream-server: point to stream-server container in registry

charts/edge-site/Chart.yaml
- foxglove/data-platform#1178
- foxglove/data-platform#1173
None.
Update the edge controller to include schemaless MCAP support and to remove message count functionality.
</td><td>
=> edge-site: bump version to include schemaless support

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/values.yaml
- Changed: if a file is provided with an invalid device name or ID, the import will fail immediately rather than being retried repeatedly.
- Added: MCAP files containing channels with schema ID 0 (no schema) will be successfully imported.
- Added: Inbox listener will sort messages in files by their log time while importing. See https://docs.foxglove.dev/docs/primary-sites/self-hosting/inbox-listener-configuration for configuration options relating to this change.
- Fixed: when a stream server pod is sent SIGTERM, it waits for`SHUTDOWN_TIMEOUT` seconds for any open requests to complete. Previously when this timeout was exceeded, the stream server would exit uncleanly and log an error. After this change, the stream server logs a warning and exits cleanly.
- Added: stream server will serve …
=> bump primary site to v0.0.41

charts/edge-site/Chart.yaml
Fixed: the device name pattern no longer allows `~`
Fixed: treat an undefined `retainRecordingsSeconds` as indefinite
None. Documented by the public device API.
https://github.com/foxglove/data-platform/commit/eaa9e6d083ab3fe828d28dc71ac3b64cd341eb69
=> Edge site bump to fix deviceName pattern

charts/primary-site/Chart.yaml
Fixed: recordings with no device ID and no specified key are imported correctly. Previously, they were incorrectly de-duplicated.
None.
=> Bump primary site to v0.0.42

charts/primary-site/Chart.yaml
Fixed: ensure the storage object writer closes successfully when writing mcap metadata. Previously, the error was suppressed, and a metadata file could fail to exist in the lake.
None
=> Bump primary site to v0.0.43

charts/primary-site/values.yaml
None. 
This is already documented here: https://docs.foxglove.dev/docs/primary-sites/self-hosting/installation#tag/Layouts/paths/~1layouts/get but not in comments.
=> primary-site: document s3_compatible support

charts/primary-site/Chart.yaml
- Changed: the inbox listener will write lake files with a new object path schema, where object paths start with `v1/`. 
Will update changelog after merging.
Fixes: FG-7924
=> primary-site: bump to v0.0.44

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/stream-service.yaml
- Added: support for downloading quarantined pending imports. This feature will be enabled through the UI in the near future.
-  Note: For this to work, deployers will need to double-check permissions on their inbox bucket to make sure that their *stream service* has access to read from them.
- Added: support for retrying quarantined pending imports. This feature will be enabled through the UI in the near future.
- Fixed: if the garbage collector cannot delete a temp file, it will log an error instead of aborting.
- Fixed: the request ID tag in inbox listener logs now matches the request ID in the foxglove API for pending imports.
- Fixed: various corrupt BAG and MCAP errors will now result in the file being quarantined immediately rather than retrying 3 times. …
=> Primary site: release v0.0.46

charts/primary-site/templates/deployments/_inbox-container.tpl, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/services/site-controller.yaml, charts/primary-site/values.yaml
- Feature: add support for built-in inbox-listener autoscaling, see [documentation](https://docs.foxglove.dev/docs/primary-sites/self-hosting/autoscaling#inbox-listener) for details
https://docs.foxglove.dev/docs/primary-sites/self-hosting/autoscaling#inbox-listener
Autoscaling can now be enabled automatically for inbox-listener. Requires KEDA to be installed as a prerequisite.
</td><td>
Fixes: FG-8702
Fixes: FG-7045
Fixes: FG-8694
=> primary-site: add KEDA based autoscaling support to inbox-listener

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/values.yaml
inbox-listener: for built-in autoscaling, add Helm chart values to tune `pollingInterval`, `successJobsHistoryLimit` and `failedJobsHistoryLimit`
</td><td>
=> add pollingInterval, successfulJobsHistoryLimit, failedJobsHistory values

charts/edge-site/Chart.yaml
Fixed: When the edge controller attempts to submit a recording that Foxglove cloud considers invalid, it will gracefully drop the recording instead of retrying forever.
=> edge-site: bump version

charts/primary-site/Chart.yaml
- Added:  If the `LOG_REPEATED_IMPORT_FAILURES` environment variable is set to `true`, the inbox listener will log an error-level message whenever it has to quarantine an input file after exhausting all retries. This can help primary site operators detect issues with their deployment.
- Changed: For primary sites using Azure storage buckets with hierarchical namespaces enabled, the garbage-collector service will log an `info`-level message when it attempts to delete a non-empty directory, but it will skip over it.
- Fixed: If the inbox listener attempts to process an MCAP file with an invalid file offset, it will quarantine the file immediately rather than retrying three times.
=> primary-site: update to v0.0.49

charts/primary-site/Chart.yaml
- Change: a device name specified in foxglove MCAP metadata will now create the device if it does not yet exist
- https://github.com/foxglove/docs/pull/431
- https://github.com/foxglove/docs/pull/458
https://github.com/foxglove/data-platform/pull/1271
FG-8580
=> primary-site: update to v0.0.50

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml
- Added: expose primary site configuration for edge controller through helm chart values.
https://github.com/foxglove/docs/pull/481
It's possible to use an edge controller with a hosted primary site, but right now users don't have a good way to configure that. This PR plumbs through a configuration variable for this.
=> edge-controller: configure primary site mode through values

charts/edge-site/templates/NOTES.txt, charts/primary-site/templates/NOTES.txt
Update links to documentation in `NOTES.txt` for charts.
Fixes: FG-9549
Update links to documentation.
=> update links to documentation

charts/edge-site/Chart.yaml, charts/primary-site/Chart.yaml
None
None
Release `edge-site`:`0.0.31` and `primary-site`:`0.0.52`.
=> bump versions of both charts with updated documentation links

charts/primary-site/Chart.yaml
primary-site: Add `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` support to primary site services
None
Bump chart version with environment variable proxy support.
=> bump primary site to 0.0.54

charts/primary-site/Chart.yaml, charts/primary-site/values.yaml
primary-site:
* fix: default HTTP/HTTPS proxy egress to disabled
None
Default HTTP/HTTPS proxy egress to disabled.
=> primary-site: default HTTP/HTTPS proxy egress to disabled

charts/edge-site/Chart.yaml, charts/edge-site/templates/statefulset.yaml, charts/edge-site/values.yaml, charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/_inbox-container.tpl, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
edge-site: add support extra custom volumes, init containers and image names
primary-site: add support extra custom volumes, init containers and image names
None
Add support for custom volumes and init containers in all Helm charts. Also move image names to a chart value. 
This should allow end users to specify custom credentials and workflows enabling more advanced usecases like adding a trusted certificate chain.
Fixes: FG-9734
=> add volume, image, init customization support to helm charts

charts/primary-site/Chart.yaml, charts/primary-site/templates/cronjobs/garbage-collector.yaml
Fix: Add HTTP proxy support to garbage collector
None
Add HTTP proxying support to garbage collector cronjob.
=> add proxy support to garbage collector

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
The chart now defaults to the new stream server image. There is a flag to opt out, however this will eventually be removed.
Docs PR incoming.
This change updates the helm charts to default to the new version of the stream server. It also adds in an option that can be enabled to revert back to the old stream server.
=> Update primary site to default to beta stream service

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
Bumps the version to v0.0.60 and renames the opt-out flag to `useLegacyImage`.
=> Release version v0.0.60

charts/primary-site/Chart.yaml
- Fixed: streaming from non-default AWS regions works.
https://github.com/foxglove/docs/pull/605
</td><td>
=> primary-site: release v0.0.62

charts/primary-site/Chart.yaml
- Added: inbox listener supports configuring the device for a recording using the `foxglove_device_name` metadata key.
https://github.com/foxglove/docs/pull/627
</td><td>
=> primary-site: bump version

charts/primary-site/Chart.yaml
- Fixed: Setting device name in object metadata when uploading to inbox now results in a recording associated with that device, rather than a deviceless recording.
- Changed: Buffered sequence node default changed from 32 to 0.
</td><td>
=> primary-site: bump version to v0.0.64

charts/primary-site/Chart.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/values.yaml
- remove "useLegacyImage" option for stream server
None
Removes the "useLegacyImage" from the chart, since the legacy image is no longer deployed.
=> primary-site: remove legacy stream server, bump to 0.0.70

charts/primary-site/Chart.yaml, charts/primary-site/templates/_helpers.tpl, charts/primary-site/templates/cronjobs/garbage-collector.yaml, charts/primary-site/templates/deployments/inbox-listener.yaml, charts/primary-site/templates/deployments/indexer.yaml, charts/primary-site/templates/deployments/site-controller.yaml, charts/primary-site/templates/deployments/stream-service.yaml, charts/primary-site/templates/serviceaccounts/garbage-collector.yaml, charts/primary-site/templates/serviceaccounts/indexer.yaml, charts/primary-site/templates/services/site-controller.yaml, charts/primary-site/values.schema.json, charts/primary-site/values.yaml
- Add support for index-in-place primary sites
- stream server: fixed a bug in the stream server where start and end times before the unix epoch would result in a 500 internal server error.
None
Adds `indexingStrategy` and `indexInPlace.storageProvider`/`.bucketName` global values, and the new indexer service. Various templates are toggled using the `indexingStrategy` enum.
=> primary-site: add index-in-place strategy, bump to 0.0.74

charts/primary-site/templates/deployments/_inbox-container.tpl, charts/primary-site/values.yaml
- Removed: the inbox listener `useLegacyImage` configuraiton value has been removed. The legacy image is no longer available.
</td><td>
=> primary-site: remove legacy inbox listener

charts/primary-site/templates/serviceaccounts/query-service.yaml
- primary site: fixed a bug introduced in v0.0.76 where the query service service account object not be created if enabled.
None.
it looks like when renaming the stream service to query service, I didn't properly namespace the values used in the query-service serviceaccount template.
Fixes: FIRE-159
</td><td>
=> add service account properly
